### PR TITLE
ci: Deploying to Maven central

### LINKED ISSUE #37: Publish to Maven Central
```[tasklist]
### Tasks
- [ ] Publish to Maven Central during the release process
- [ ] Update readme to include updated install instructions
```

### PR DESCRIPTION
**Pull request by nicklasl**
## This PR
- Adds the required build configurations and CI steps to publish the artifact to sonatype staging and maven central

### Related Issues

Fixes #37

### CODE REVIEW

**Review by toddbaert — APPROVED** [review]
Scanning through this I don't see any problems, things looks correct as far as I can tell.

Let me know how it goes. If things don't work as you'd expect we can meet and do troubleshooting.

**Comment by beeme1mr** [comment]
It looks like we need to configure the secrets before merging. I'll work with @toddbaert on that.

**Comment by toddbaert** [comment]
@nicklasl I've added `OSSRH_PASSWORD` and `OSSRH_USERNAME` in the repo secrets.

**Comment by nicklasl** [comment]
Thanks, we'll look at merging this tomorrow and try to craft a release to test it out 👍

**Review by beeme1mr — APPROVED** [review]

**Comment by beeme1mr** [comment]
@nicklasl I'll merge this PR since it won't actually trigger a release.

**Pull request merged**
